"""add_proxy_vault_tables

Revision ID: 11f2bdd3872a
Revises: 412b1b583333
Create Date: 2026-06-06 20:30:59.473906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11f2bdd3872a'
down_revision: Union[str, None] = '412b1b583333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted_key', sa.String(length=1024), nullable=False),
    sa.Column('key_hint', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_keys_tenant_id'), 'provider_keys', ['tenant_id'], unique=False)
    op.create_table('proxy_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('allowed_providers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('monthly_cap_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fallback_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_keys_key_hash'), 'proxy_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_proxy_keys_tenant_id'), 'proxy_keys', ['tenant_id'], unique=False)
    op.create_table('usage_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('proxy_key_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proxy_key_id'], ['proxy_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_alerts_proxy_key_id'), 'usage_alerts', ['proxy_key_id'], unique=False)
    op.create_index(op.f('ix_usage_alerts_tenant_id'), 'usage_alerts', ['tenant_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proxy_key_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proxy_key_id'], ['proxy_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_proxy_key_id'), 'usage_logs', ['proxy_key_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_tenant_id'), 'usage_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_logs_tenant_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_proxy_key_id'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_usage_alerts_tenant_id'), table_name='usage_alerts')
    op.drop_index(op.f('ix_usage_alerts_proxy_key_id'), table_name='usage_alerts')
    op.drop_table('usage_alerts')
    op.drop_index(op.f('ix_proxy_keys_tenant_id'), table_name='proxy_keys')
    op.drop_index(op.f('ix_proxy_keys_key_hash'), table_name='proxy_keys')
    op.drop_table('proxy_keys')
    op.drop_index(op.f('ix_provider_keys_tenant_id'), table_name='provider_keys')
    op.drop_table('provider_keys')
    # ### end Alembic commands ###
